# Generated by Django 5.0.1 on 2026-02-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category display name (must be unique)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated from name if not provided)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional category description for category pages')),
                ('image', models.ImageField(blank=True, help_text='Category thumbnail image', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive categories are hidden from the store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product display name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (must be unique)', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed product description (supports markdown)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in base currency (e.g., USD). Use Decimal for accuracy.', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/')),
                ('inventory_count', models.PositiveIntegerField(default=0, help_text='Number of items in stock (cannot be negative)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive products are hidden from the store')),
                ('featured', models.BooleanField(db_index=True, default=False, help_text='Featured products appear on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category (required). Deleting category deletes products.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'), models.Index(fields=['featured', 'is_active'], name='products_pr_feature_80c52d_idx'), models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'), models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx')],
            },
        ),
    ]
